const wishlistTypes = {
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  FETCH_WISHLIST: "FETCH_WISHLIST",
  SET_WISHLIST: "SET_WISHLIST",
  CHECK_WISHLIST_START: "CHECK_WISHLIST_START",
  CHECK_WISHLIST_SUCCESS: "CHECK_WISHLIST_SUCCESS",
  REMOVE_WISHLIST: "REMOVE_WISHLIST",
  REMOVE_WISHLIST_SUCCESS: "REMOVE_WISHLIST_SUCCESS",
};
export default wishlistTypes;
