const productsTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  UPDATE_PRODUCT_START: "UPDATE_PRODUCT_START",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  SET_PRODUCT: "SET_PRODUCT",
  FETCH_ALL_PRODUCTS: "FETCH_ALL_PRODUCTS",
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
  RESET_LOADING: "RESET_LOADING",
  DONE_ACTION: "DONE_ACTION",
  DONE_DELETE: "DONE_DELETE",
};

export default productsTypes;
